('CS1336','1','Ability to develop algorithmic solutions for use on computers'),
('CS1336','2','Ability to express algorithmic solutions in a high level computer language  '),
('CS1336','3','Ability to utilize fundamental programming structures in linear processing'),
('CS1336','4','Ability to utilize fundamental programming structures in conditional processing'),
('CS1336','5','Ability to utilize fundamental programming structures in loop processing'),
('CS1336','6','Ability to process data in arrays'),
('CS1336','7','Ability to develop programs in a functional or method form'),
('CS1336','8','Ability to perform searches and sorts'),
('CS1336','9','Ability to utilize reference variables'),
('CS1336','10','Ability to manipulate character and string data'),
('CS1336','11','Ability to perform sequential file input and output'),
('CS1337','1','Ability to develop object oriented software solutions for use on computers  '),
('CS1337','2','Ability to express algorithmic solutions in a high level computer language  '),
('CS1337','3','Ability to utilize the String classes'),
('CS1337','4','Ability to utilize express multiclass relationships among objects'),
('CS1337','5','Ability to implement graphical user interfaces'),
('CS1337','6','Ability to develop graphical programs utilizing standard layout managers'),
('CS1337','7','Ability to develop event driven programs'),
('CS1337','8','Ability to process data with abstract data types'),
('CS2305','1','Ability to understand mathematical facts in order to read comprehend and construct mathematical arguments '),
('CS2305','2','Ability to use and apply basic definitons and properties of sets and logic'),
('CS2305','3','Ability to specify precise meaning of mathematical statements using quantifiers and predicates as needed'),
('CS2305','4','Ability to recognize and construct valid proofs'),
('CS2305','5','Ability to understand and use various types of functions'),
('CS2336','1','Ability to implement a comprehensive OO application'),
('CS2336','2','Ability to create and use primitive data structures'),
('CS2336','3','Ability to use core Java data structures in stack, queue, tree'),
('CS2336','4','Ability to use core Java data structures in lists'),
('CS2336','5','Ability to use core Java data structures in maps'),
('CS2336','6','Ability to implement a GUI for user interaction'),
('CS2336','7','Ability to create and use exception handlers'),
('CS2336','8','Ability to create and use graphical error messages'),
('CS2336','9','Ability to use file input/output with information assurance in text files'),
('CS2336','10','Ability to use file input/output with information assurance in object files'),
('CS3305','1','Ability to use Big O in context of algorithmic complexity'),
('CS3305','2','Ability to construct and solve recurrence relations'),
('CS3305','3','Ability to use the principle of inclusion and exclusion to solve problems'),
('CS3305','4','Ability to understand binary relations and their applications'),
('CS3305','5','Ability to recognize and use equivalence relations and partial orderings'),
('CS3305','6','Ability to use and construct graphs and graph terminology'),
('CS3341','1','Ability to understand basic properties of probability theory'),
('CS3341','2','Ability to understand concepts of conditional probability Bayes Theorem independence'),
('CS3341','3','Ability to understand basic concepts and properties of discrete random variables'),
('CS3341','4','Ability to understand expectations and functions of discrete random variables'),
('CS3341','5','Ability to understand basic concepts and properties of continuous random variables'),
('CS3341','6','Ability to understand expectations and functions of continuous random variables'),
('CS6363','1','Ability to use asymptotic notations'),
('CS6363','2','Ability to perform simple algorithm analysis'),
('CS6363','3','A knowledge of basic proof techniques'),
('CS6363','4','Understand and use linked list and stack'),
('CE4347','1','Understand Data Modeling'),
('CE4347','2','Understand the Relational Model and theory'),
('CE4347','3','Understand normalization of relations'),
('CE4347','4','Gain a fundamental understanding of SQL programming'),
('CE4347','5','Understand data organization methods, indexing, and query processing'),
('CE4347','6','Understand database integrity and concurrency'),
('CE4348','1','An understanding of basic elements of computer system hardware'),
('CE4348','2','An understanding of modern operating systems'),
('CE4348','3','An understanding of processes'),
('CE4348','4','An understanding of threads'),
('CE4348','5','An understanding of concurrency issues'),
('CE4348','6','An understanding of simple memory management'),
('CE4348','7','An understanding of virtual memory'),
('CE4348','8','An understanding of scheduling algorithms'),
('EE6324','1','Conventional Encryption Algorithms'),
('EE6324','2','Cryptanalysis'),
('EE6324','3','Public Key Cryptography'),
('EE6324','4','Stack Overflow Attacks'),
('EE6324','5','Operating Systems Securitys'),
('CS6360','1','ER and EER Relational Conceptual Data Model'),
('CS6360','2','Relational Data Model'),
('CS6360','3','ER/EER to Relational Data Model Mapping'),
('CS6360','4','Query Languges (Relational Algebra, SQL, etc)'),
('CS6360','5','Query Processing and Optimization'),
('CS6360','6','Functional Dependency and Normalization'),
('CS6360','7','Transaction Processing Concepts'),
('CS6360','8','Concurrency Control Techniques'),
('CS6360','9','Recovery')
